import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

interface OpenApiDocument {
  openapi: string;
  paths: Record<string, Record<string, unknown>>;
  components: {
    securitySchemes?: Record<string, unknown>;
    schemas?: Record<string, unknown>;
  };
}

const document = JSON.parse(
  readFileSync("contracts/openapi/backend-api.json", "utf8"),
) as OpenApiDocument;

const expectedOperations = new Map<string, string[]>([
  ["/health/live", ["get"]],
  ["/health/ready", ["get"]],
  ["/auth/login", ["post"]],
  ["/auth/refresh", ["post"]],
  ["/auth/logout", ["post"]],
  ["/auth/me", ["get"]],
  ["/api/conversations", ["get"]],
  ["/api/conversations/summary", ["get"]],
  ["/api/comments/moderation-summary", ["get"]],
  ["/api/comments", ["get"]],
  ["/api/comments/stats", ["get"]],
  ["/api/comments/control", ["get"]],
  ["/api/comments/settings", ["get", "put"]],
  ["/api/comments/{comment_public_id}/reply", ["post"]],
  ["/api/comments/{comment_public_id}/hide", ["post"]],
  ["/api/comments/{comment_public_id}/delete", ["post"]],
  ["/api/comments/{comment_public_id}/manual", ["post"]],
  ["/api/comments/{comment_public_id}/ai-suggestion", ["post"]],
  ["/api/sms/templates", ["get", "post"]],
  ["/api/sms/templates/{template_public_id}", ["patch", "delete"]],
  ["/api/sms/history", ["get"]],
  ["/api/sms/manual-send", ["post"]],
  ["/api/sms/automatic/trigger", ["post"]],
  ["/api/reports/analysis", ["get"]],
  ["/api/instagram/publications", ["post"]],
  ["/api/instagram/publications/{publication_public_id}", ["get"]],
  ["/api/instagram/insights/account", ["get"]],
  ["/api/instagram/insights/account/refresh", ["post"]],
  ["/api/conversations/{conversation_public_id}/messages", ["get", "post"]],
  ["/api/conversations/{conversation_public_id}/state", ["patch"]],
  ["/api/conversations/{conversation_public_id}/notes", ["patch"]],
  ["/api/conversations/{conversation_public_id}/customer-notes", ["patch"]],
  ["/api/message-shortcuts", ["get", "post"]],
  ["/api/message-shortcuts/{shortcut_public_id}", ["delete", "patch"]],
  ["/api/ai/reply-suggestion", ["post"]],
  ["/api/customers", ["get"]],
  ["/api/customers/summary", ["get"]],
  ["/api/customers/{customer_public_id}", ["get", "patch"]],
  ["/api/customers/{customer_public_id}/notes", ["patch"]],
  ["/api/orders", ["get", "post"]],
  ["/api/orders/customer-lookup", ["get"]],
  ["/api/orders/product-options", ["get"]],
  ["/api/orders/summary", ["get"]],
  ["/api/orders/{order_public_id}/status", ["patch"]],
  ["/api/orders/{order_public_id}/payment-request", ["post"]],
  ["/api/orders/bulk/confirmation-calls", ["post"]],
  ["/api/orders/bulk/kolaybi-transfer", ["post"]],
  ["/api/orders/{order_public_id}", ["delete"]],
  ["/api/orders/{order_public_id}/actions", ["get"]],
  ["/api/orders/{order_public_id}/provider-sync", ["post"]],
  ["/api/orders/{order_public_id}/notes", ["patch"]],
  ["/api/orders/{order_public_id}/confirmation", ["patch"]],
  ["/api/orders/{order_public_id}/cancel", ["post"]],
  ["/api/orders/{order_public_id}/restore", ["post"]],
  ["/api/orders/{order_public_id}/kolaybi/transfer", ["post"]],
  ["/api/orders/{order_public_id}/kolaybi/e-document", ["post"]],
  ["/api/orders/{order_public_id}/kolaybi/invoice", ["post"]],
  ["/api/orders/{order_public_id}/confirmation-call", ["post"]],
  ["/api/orders/{order_public_id}/confirmation-call/status", ["post"]],
  ["/api/balances/summary", ["get"]],
  ["/api/balances/staff", ["get"]],
  ["/api/balances/staff/{user_public_id}/orders", ["get"]],
  ["/api/balances/staff/{user_public_id}/reset", ["post"]],
  ["/api/balances/movements", ["get"]],
  ["/api/balances/payment-requests", ["get", "post"]],
  ["/api/balances/payment-requests/{payment_request_public_id}/approve", ["post"]],
  ["/api/balances/payment-requests/{payment_request_public_id}/reject", ["post"]],
  ["/api/accounting/contacts", ["get", "post"]],
  ["/api/accounting/contacts/{contact_public_id}", ["get", "patch"]],
  ["/api/accounting/invoices", ["get", "post"]],
  ["/api/accounting/invoices/{invoice_public_id}", ["get"]],
  ["/api/accounting/invoices/{invoice_public_id}/document", ["get"]],
  ["/api/accounting/invoices/{invoice_public_id}/payments", ["post"]],
  ["/api/accounting/invoices/{invoice_public_id}/cancel", ["post"]],
  ["/api/accounting/kolaybi/status", ["get"]],
  ["/api/accounting/kolaybi/sync", ["post"]],
  ["/api/debug/whatsapp", ["get"]],
  ["/api/debug/whatsapp/test-send", ["post"]],
  ["/api/debug/instagram", ["get"]],
  ["/api/debug/ai", ["get"]],
  ["/api/debug/ai/test", ["post"]],
  ["/api/debug/ai-training/stats", ["get"]],
  ["/api/debug/ai-training/export", ["get"]],
  ["/api/products", ["get", "post"]],
  ["/api/products/summary", ["get"]],
  ["/api/products/{product_public_id}", ["delete", "patch"]],
  ["/api/products/{product_public_id}/stock-movements", ["get", "post"]],
  ["/api/shipments", ["get"]],
  ["/api/shipments/summary", ["get"]],
  ["/api/shipments/pipeline-summary", ["get"]],
  ["/api/shipments/{shipment_public_id}", ["get"]],
  ["/api/shipments/{shipment_public_id}/status", ["patch"]],
  ["/api/shipments/{shipment_public_id}/track", ["post"]],
  ["/api/orders/{order_public_id}/shipment-draft", ["get"]],
  ["/api/orders/{order_public_id}/shipments", ["post"]],
  ["/api/shipments/bulk-create", ["post"]],
  ["/api/shipments/{shipment_public_id}/print", ["get"]],
  ["/api/shipments/{shipment_public_id}/label", ["get"]],
  ["/api/shipments/{shipment_public_id}/printed", ["post"]],
  ["/api/reports/summary", ["get"]],
  ["/api/sms/send", ["post"]],
  ["/api/files/uploads", ["post"]],
  ["/api/files/multipart-uploads", ["post"]],
  ["/api/files/{file_public_id}/multipart-uploads/parts", ["post"]],
  ["/api/files/{file_public_id}/multipart-uploads/complete", ["post"]],
  ["/api/files/{file_public_id}/multipart-uploads/abort", ["post"]],
  ["/api/files/orphans", ["get"]],
  ["/api/files/{file_public_id}/orphan-cleanup-dry-run", ["post"]],
  ["/api/files/{file_public_id}/orphan-cleanup", ["post"]],
  ["/api/files/{file_public_id}/download", ["get"]],
  ["/api/files/{file_public_id}", ["get"]],
  ["/api/webphone/config", ["get"]],
  ["/api/webphone/test-call", ["post"]],
  ["/api/vapi/config", ["get", "put"]],
  ["/api/vapi/statistics", ["get"]],
  ["/api/vapi/cargo-not-received", ["get"]],
  ["/api/vapi/queue", ["get", "post"]],
  ["/api/vapi/queue/{queue_public_id}", ["delete"]],
  ["/api/vapi/calls", ["get", "post"]],
  ["/api/vapi/calls/bulk", ["post"]],
  ["/api/vapi/calls/{call_public_id}", ["get"]],
  ["/api/vapi/webhooks", ["get"]],
  ["/api/vapi/webhooks/{event_public_id}", ["get"]],
  ["/api/netgsm/status", ["get"]],
  ["/api/netgsm/teyit-settings", ["get", "put"]],
  ["/api/netgsm/cdr/sync", ["post"]],
  ["/api/netgsm/webhook/sesli-mesaj", ["get", "post"]],
  ["/api/netgsm/cdr", ["get"]],
  ["/api/netgsm/cdr/istatistik", ["get"]],
  ["/api/netgsm/sesli-mesaj", ["get", "post"]],
  ["/api/netgsm/sesli-mesaj/{publicId}", ["get"]],
  ["/api/netgsm/sesli-mesaj/{publicId}/rapor", ["post"]],
  ["/api/netgsm/rehber", ["get"]],
  ["/admin/settings", ["get"]],
  ["/admin/settings/{key}", ["put"]],
  ["/admin/settings/{key}/versions", ["get"]],
  ["/admin/settings/{key}/rollback", ["post"]],
  ["/admin/integrations/providers", ["get"]],
  ["/admin/integrations/provider-catalog", ["get"]],
  ["/admin/integrations/accounts", ["get", "post"]],
  ["/admin/integrations/accounts/{account_public_id}", ["get"]],
  ["/admin/integrations/accounts/{account_public_id}/analytics-summary", ["get"]],
  ["/admin/integrations/accounts/{account_public_id}/settings/{key}", ["put"]],
  ["/admin/integrations/accounts/{account_public_id}/tokens/{token_type}", ["put"]],
  ["/admin/integrations/provider-attempts", ["get"]],
  ["/admin/integrations/provider-debug-summary", ["get"]],
  ["/admin/integrations/provider-cron-triggers/{provider_key}", ["post"]],
  ["/admin/integrations/instagram-publish-previews", ["post"]],
  ["/admin/integrations/netgsm/balance", ["get"]],
  ["/admin/users", ["get", "post"]],
  ["/admin/users/{user_public_id}", ["patch", "delete"]],
  ["/admin/logs", ["get"]],
  ["/admin/data-deletion-requests", ["get"]],
  ["/admin/data-deletion-requests/{public_id}", ["patch"]],
  ["/api/veri-silme-talebi", ["post"]],
  ["/api/veri-silme-talebi/{reference}", ["get"]],
  ["/api/facebook/data-deletion", ["post"]],
  ["/auth/account/profile", ["patch"]],
  ["/auth/account/password", ["post"]],
  ["/api/app-settings/ai-status", ["get"]],
]);

describe("backend OpenAPI contract", () => {
  it("pins the backend-owned route surface consumed by the web app", () => {
    expect(document.openapi).toBe("3.1.0");
    expect(Object.keys(document.paths).sort()).toEqual([...expectedOperations.keys()].sort());

    for (const [path, methods] of expectedOperations) {
      expect(Object.keys(document.paths[path] ?? {}).sort()).toEqual(methods.sort());
    }
  });

  it("keeps auth, admin, domain, file, and webphone schemas named", () => {
    expect(document.components.securitySchemes?.bearerAuth).toBeDefined();
    expect(Object.keys(document.components.schemas ?? {})).toEqual(
      expect.arrayContaining([
        "AuthSession",
        "AuthUser",
        "Conversation",
        "ListMeta",
        "ConversationList",
        "ConversationSummaryStats",
        "CommentModerationSummary",
        "Comment",
        "CommentList",
        "CommentStats",
        "CommentModerationConfig",
        "CommentSettingsResponse",
        "CommentControlReport",
        "CommentReplyRequest",
        "CommentActionRequest",
        "CommentActionResponse",
        "CommentAiSuggestionResponse",
        "AdminUser",
        "AdminUserList",
        "AdminLogList",
        "NetgsmBalance",
        "BalanceSummary",
        "StaffBalanceList",
        "BalanceMovementList",
        "BalancePaymentRequest",
        "BalancePaymentRequestList",
        "CreateBalancePaymentRequest",
        "BalancePaymentRequestResult",
        "ProcessBalancePaymentRequestResult",
        "BalanceResetResult",
        "StaffOrderList",
        "UpdateConversationStateRequest",
        "UpdateNoteRequest",
        "Message",
        "MessageAttachment",
        "MessageAttachmentInput",
        "MessageShortcut",
        "MessageShortcutList",
        "CreateMessageShortcutRequest",
        "UpdateMessageShortcutRequest",
        "AiReplySuggestionRequest",
        "AiReplySuggestionResponse",
        "Customer",
        "CustomerList",
        "CustomerSummaryStats",
        "Order",
        "OrderSummaryStats",
        "Product",
        "ProductList",
        "ProductSummaryStats",
        "CreateProductRequest",
        "UpdateProductRequest",
        "CreateStockMovementRequest",
        "StockMovement",
        "StockMovementList",
        "StockMovementResult",
        "CreatePaymentRequest",
        "PaymentRequestResponse",
        "SendSmsRequest",
        "VapiCallPolicy",
        "VapiStatisticsResponse",
        "VapiCargoNotReceivedList",
        "VapiQueueList",
        "VapiQueueAddRequest",
        "VapiCall",
        "VapiCallList",
        "VapiStartCallRequest",
        "VapiBulkCallResponse",
        "VapiCallDetailResponse",
        "VapiWebhookEventList",
        "NetgsmTeyitSettings",
        "NetgsmCdrSyncRequest",
        "NetgsmCdrListResponse",
        "NetgsmCdrStatisticsResponse",
        "SendSmsResponse",
        "OrderActionState",
        "OrderProviderStep",
        "OrderActionsResponse",
        "OrderProviderStepResponse",
        "OrderDeleteResponse",
        "OrderBulkActionRequest",
        "OrderBulkActionResponse",
        "SmsTemplate",
        "SmsTemplateList",
        "SmsTemplateResponse",
        "CreateSmsTemplateRequest",
        "UpdateSmsTemplateRequest",
        "SmsMessage",
        "SmsHistoryList",
        "ManualSmsSendRequest",
        "ManualSmsSendResponse",
        "AutomaticSmsTriggerRequest",
        "AutomaticSmsTriggerResponse",
        "Shipment",
        "ShipmentTrackingEvent",
        "ShipmentSummaryStats",
        "ShipmentPipelineSummary",
        "ShipmentPipelineRow",
        "TrackShipmentRequest",
        "TrackShipmentResponse",
        "ShipmentDraft",
        "ShipmentDraftItem",
        "ShipmentMeasurements",
        "CreateShipmentRequest",
        "CreateShipmentResponse",
        "BulkCreateShipmentsRequest",
        "BulkCreateShipmentsResponse",
        "ShipmentPrint",
        "MarkShipmentPrintedRequest",
        "MarkShipmentPrintedResponse",
        "ReportSummary",
        "ReportAnalysis",
        "InstagramPublishRequest",
        "InstagramPublishResponse",
        "InstagramPublication",
        "InstagramAccountInsights",
        "FileUpload",
        "FileOrphanList",
        "FileOrphanCleanupDryRun",
        "WebphoneConfig",
        "WebphoneTestCallRequest",
        "Setting",
        "SettingVersion",
        "SettingVersionList",
        "SettingRollbackRequest",
        "IntegrationAccountSnapshot",
        "InstagramAnalyticsSummary",
        "InstagramPublishPreviewRequest",
        "ProviderAttempt",
        "ProviderCatalogList",
        "ProviderDebugSummary",
        "ProviderCronTriggerRequest",
      ]),
    );
  });

  it("keeps login and health routes explicitly public", () => {
    expect(document.paths["/auth/login"]?.post).toMatchObject({ security: [] });
    expect(document.paths["/auth/refresh"]?.post).toMatchObject({ security: [] });
    expect(document.paths["/health/live"]?.get).toMatchObject({ security: [] });
    expect(document.paths["/health/ready"]?.get).toMatchObject({ security: [] });
  });
});
